services:
  backend:
    build: backend
    restart: always
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    build: frontend
    restart: always
    ports:
      - "3000:3000"

  database:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
