# Generated by Django 4.2.6 on 2023-10-21 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0003_remove_produto_id_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
