# Generated by Django 4.2.6 on 2023-10-21 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0004_alter_venda_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papelaria.venda'),
        ),
    ]
