# Generated by Django 4.2.6 on 2023-10-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0005_alter_itemvenda_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='papelaria.venda'),
            preserve_default=False,
        ),
    ]
