# Generated by Django 4.2.6 on 2023-10-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0006_alter_itemvenda_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.AddField(
            model_name='venda',
            name='itens',
            field=models.ManyToManyField(related_name='venda', to='papelaria.itemvenda'),
        ),
    ]
