# Generated by Django 4.2.6 on 2023-10-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0007_remove_itemvenda_venda_remove_venda_produtos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='itens',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='papelaria.venda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(through='papelaria.ItemVenda', to='papelaria.produto'),
        ),
    ]
