# Generated by Django 4.2.6 on 2023-10-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0008_remove_venda_itens_itemvenda_venda_venda_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
