# Generated by Django 4.2.6 on 2023-10-25 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papelaria', '0011_alter_venda_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 23, 6, 35, 288973)),
        ),
    ]
